// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.9
// source: schemas/sample.proto

package schemas

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Columns struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RowNo     uint32 `protobuf:"varint,1,opt,name=rowNo,proto3" json:"rowNo,omitempty"`
	FirstName string `protobuf:"bytes,2,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName  string `protobuf:"bytes,3,opt,name=lastName,proto3" json:"lastName,omitempty"`
	Age       uint32 `protobuf:"varint,4,opt,name=age,proto3" json:"age,omitempty"`
}

func (x *Columns) Reset() {
	*x = Columns{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schemas_sample_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Columns) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Columns) ProtoMessage() {}

func (x *Columns) ProtoReflect() protoreflect.Message {
	mi := &file_schemas_sample_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Columns.ProtoReflect.Descriptor instead.
func (*Columns) Descriptor() ([]byte, []int) {
	return file_schemas_sample_proto_rawDescGZIP(), []int{0}
}

func (x *Columns) GetRowNo() uint32 {
	if x != nil {
		return x.RowNo
	}
	return 0
}

func (x *Columns) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *Columns) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *Columns) GetAge() uint32 {
	if x != nil {
		return x.Age
	}
	return 0
}

var File_schemas_sample_proto protoreflect.FileDescriptor

var file_schemas_sample_proto_rawDesc = []byte{
	0x0a, 0x14, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x73, 0x2f, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x22, 0x6b,
	0x0a, 0x07, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x6f, 0x77,
	0x4e, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x72, 0x6f, 0x77, 0x4e, 0x6f, 0x12,
	0x1c, 0x0a, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x6c, 0x61, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x6c, 0x61, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x67, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x61, 0x67, 0x65, 0x42, 0x4a, 0x0a, 0x16, 0x75,
	0x6e, 0x61, 0x72, 0x79, 0x6f, 0x6e, 0x65, 0x2e, 0x70, 0x62, 0x6f, 0x75, 0x74, 0x2e, 0x73, 0x63,
	0x68, 0x65, 0x6d, 0x61, 0x73, 0x50, 0x01, 0x5a, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x7a, 0x7a, 0x79, 0x6f, 0x7a, 0x62, 0x6f, 0x75, 0x72, 0x6e, 0x65,
	0x2f, 0x75, 0x6e, 0x61, 0x72, 0x79, 0x6f, 0x6e, 0x65, 0x2f, 0x70, 0x62, 0x6f, 0x75, 0x74, 0x2f,
	0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_schemas_sample_proto_rawDescOnce sync.Once
	file_schemas_sample_proto_rawDescData = file_schemas_sample_proto_rawDesc
)

func file_schemas_sample_proto_rawDescGZIP() []byte {
	file_schemas_sample_proto_rawDescOnce.Do(func() {
		file_schemas_sample_proto_rawDescData = protoimpl.X.CompressGZIP(file_schemas_sample_proto_rawDescData)
	})
	return file_schemas_sample_proto_rawDescData
}

var file_schemas_sample_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_schemas_sample_proto_goTypes = []interface{}{
	(*Columns)(nil), // 0: sample.columns
}
var file_schemas_sample_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_schemas_sample_proto_init() }
func file_schemas_sample_proto_init() {
	if File_schemas_sample_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_schemas_sample_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Columns); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_schemas_sample_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_schemas_sample_proto_goTypes,
		DependencyIndexes: file_schemas_sample_proto_depIdxs,
		MessageInfos:      file_schemas_sample_proto_msgTypes,
	}.Build()
	File_schemas_sample_proto = out.File
	file_schemas_sample_proto_rawDesc = nil
	file_schemas_sample_proto_goTypes = nil
	file_schemas_sample_proto_depIdxs = nil
}
