// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.9
// source: xlsxserver.proto

package pbout

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SaveInGRPCClient is the client API for SaveInGRPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SaveInGRPCClient interface {
	PersistValues(ctx context.Context, in *XlsxValues, opts ...grpc.CallOption) (*XlsxValuesResponse, error)
	GetXlsxValues(ctx context.Context, in *GetValRequest, opts ...grpc.CallOption) (*XlsxValues, error)
}

type saveInGRPCClient struct {
	cc grpc.ClientConnInterface
}

func NewSaveInGRPCClient(cc grpc.ClientConnInterface) SaveInGRPCClient {
	return &saveInGRPCClient{cc}
}

func (c *saveInGRPCClient) PersistValues(ctx context.Context, in *XlsxValues, opts ...grpc.CallOption) (*XlsxValuesResponse, error) {
	out := new(XlsxValuesResponse)
	err := c.cc.Invoke(ctx, "/pbout.SaveInGRPC/PersistValues", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *saveInGRPCClient) GetXlsxValues(ctx context.Context, in *GetValRequest, opts ...grpc.CallOption) (*XlsxValues, error) {
	out := new(XlsxValues)
	err := c.cc.Invoke(ctx, "/pbout.SaveInGRPC/GetXlsxValues", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SaveInGRPCServer is the server API for SaveInGRPC service.
// All implementations must embed UnimplementedSaveInGRPCServer
// for forward compatibility
type SaveInGRPCServer interface {
	PersistValues(context.Context, *XlsxValues) (*XlsxValuesResponse, error)
	GetXlsxValues(context.Context, *GetValRequest) (*XlsxValues, error)
	mustEmbedUnimplementedSaveInGRPCServer()
}

// UnimplementedSaveInGRPCServer must be embedded to have forward compatible implementations.
type UnimplementedSaveInGRPCServer struct {
}

func (UnimplementedSaveInGRPCServer) PersistValues(context.Context, *XlsxValues) (*XlsxValuesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PersistValues not implemented")
}
func (UnimplementedSaveInGRPCServer) GetXlsxValues(context.Context, *GetValRequest) (*XlsxValues, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetXlsxValues not implemented")
}
func (UnimplementedSaveInGRPCServer) mustEmbedUnimplementedSaveInGRPCServer() {}

// UnsafeSaveInGRPCServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SaveInGRPCServer will
// result in compilation errors.
type UnsafeSaveInGRPCServer interface {
	mustEmbedUnimplementedSaveInGRPCServer()
}

func RegisterSaveInGRPCServer(s grpc.ServiceRegistrar, srv SaveInGRPCServer) {
	s.RegisterService(&SaveInGRPC_ServiceDesc, srv)
}

func _SaveInGRPC_PersistValues_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(XlsxValues)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SaveInGRPCServer).PersistValues(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbout.SaveInGRPC/PersistValues",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SaveInGRPCServer).PersistValues(ctx, req.(*XlsxValues))
	}
	return interceptor(ctx, in, info, handler)
}

func _SaveInGRPC_GetXlsxValues_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetValRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SaveInGRPCServer).GetXlsxValues(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbout.SaveInGRPC/GetXlsxValues",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SaveInGRPCServer).GetXlsxValues(ctx, req.(*GetValRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SaveInGRPC_ServiceDesc is the grpc.ServiceDesc for SaveInGRPC service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SaveInGRPC_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pbout.SaveInGRPC",
	HandlerType: (*SaveInGRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PersistValues",
			Handler:    _SaveInGRPC_PersistValues_Handler,
		},
		{
			MethodName: "GetXlsxValues",
			Handler:    _SaveInGRPC_GetXlsxValues_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "xlsxserver.proto",
}
