// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.9
// source: xlsxserver.proto

package pbout

import (
	schemas "github.com/ozzyozbourne/unaryone/pbout/schemas"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateXlsxFileRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileName  string             `protobuf:"bytes,1,opt,name=fileName,proto3" json:"fileName,omitempty"`
	SheetName string             `protobuf:"bytes,2,opt,name=sheetName,proto3" json:"sheetName,omitempty"`
	Cols      []*schemas.Columns `protobuf:"bytes,3,rep,name=cols,proto3" json:"cols,omitempty"`
}

func (x *CreateXlsxFileRequest) Reset() {
	*x = CreateXlsxFileRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_xlsxserver_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateXlsxFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateXlsxFileRequest) ProtoMessage() {}

func (x *CreateXlsxFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xlsxserver_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateXlsxFileRequest.ProtoReflect.Descriptor instead.
func (*CreateXlsxFileRequest) Descriptor() ([]byte, []int) {
	return file_xlsxserver_proto_rawDescGZIP(), []int{0}
}

func (x *CreateXlsxFileRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *CreateXlsxFileRequest) GetSheetName() string {
	if x != nil {
		return x.SheetName
	}
	return ""
}

func (x *CreateXlsxFileRequest) GetCols() []*schemas.Columns {
	if x != nil {
		return x.Cols
	}
	return nil
}

type CreateXlsxFileResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Res       string `protobuf:"bytes,1,opt,name=res,proto3" json:"res,omitempty"`
	FileSaved bool   `protobuf:"varint,2,opt,name=fileSaved,proto3" json:"fileSaved,omitempty"`
}

func (x *CreateXlsxFileResponse) Reset() {
	*x = CreateXlsxFileResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_xlsxserver_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateXlsxFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateXlsxFileResponse) ProtoMessage() {}

func (x *CreateXlsxFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xlsxserver_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateXlsxFileResponse.ProtoReflect.Descriptor instead.
func (*CreateXlsxFileResponse) Descriptor() ([]byte, []int) {
	return file_xlsxserver_proto_rawDescGZIP(), []int{1}
}

func (x *CreateXlsxFileResponse) GetRes() string {
	if x != nil {
		return x.Res
	}
	return ""
}

func (x *CreateXlsxFileResponse) GetFileSaved() bool {
	if x != nil {
		return x.FileSaved
	}
	return false
}

var File_xlsxserver_proto protoreflect.FileDescriptor

var file_xlsxserver_proto_rawDesc = []byte{
	0x0a, 0x10, 0x78, 0x6c, 0x73, 0x78, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x05, 0x70, 0x62, 0x6f, 0x75, 0x74, 0x1a, 0x14, 0x73, 0x63, 0x68, 0x65, 0x6d,
	0x61, 0x73, 0x2f, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x76, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x58, 0x6c, 0x73, 0x78, 0x46, 0x69, 0x6c,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x68, 0x65, 0x65, 0x74, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x68, 0x65, 0x65, 0x74, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x23, 0x0a, 0x04, 0x63, 0x6f, 0x6c, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0f, 0x2e, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e,
	0x73, 0x52, 0x04, 0x63, 0x6f, 0x6c, 0x73, 0x22, 0x48, 0x0a, 0x16, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x58, 0x6c, 0x73, 0x78, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x72, 0x65, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x53, 0x61, 0x76, 0x65, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x53, 0x61, 0x76, 0x65,
	0x64, 0x32, 0x60, 0x0a, 0x10, 0x53, 0x61, 0x76, 0x65, 0x49, 0x6e, 0x47, 0x52, 0x50, 0x43, 0x53,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x4c, 0x0a, 0x0d, 0x50, 0x65, 0x72, 0x73, 0x69, 0x73, 0x74,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x12, 0x1c, 0x2e, 0x70, 0x62, 0x6f, 0x75, 0x74, 0x2e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x58, 0x6c, 0x73, 0x78, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x70, 0x62, 0x6f, 0x75, 0x74, 0x2e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x58, 0x6c, 0x73, 0x78, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x3a, 0x0a, 0x0e, 0x75, 0x6e, 0x61, 0x72, 0x79, 0x6f, 0x6e, 0x65, 0x2e,
	0x70, 0x62, 0x6f, 0x75, 0x74, 0x50, 0x01, 0x5a, 0x26, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x7a, 0x7a, 0x79, 0x6f, 0x7a, 0x62, 0x6f, 0x75, 0x72, 0x6e, 0x65,
	0x2f, 0x75, 0x6e, 0x61, 0x72, 0x79, 0x6f, 0x6e, 0x65, 0x2f, 0x70, 0x62, 0x6f, 0x75, 0x74, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_xlsxserver_proto_rawDescOnce sync.Once
	file_xlsxserver_proto_rawDescData = file_xlsxserver_proto_rawDesc
)

func file_xlsxserver_proto_rawDescGZIP() []byte {
	file_xlsxserver_proto_rawDescOnce.Do(func() {
		file_xlsxserver_proto_rawDescData = protoimpl.X.CompressGZIP(file_xlsxserver_proto_rawDescData)
	})
	return file_xlsxserver_proto_rawDescData
}

var file_xlsxserver_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_xlsxserver_proto_goTypes = []interface{}{
	(*CreateXlsxFileRequest)(nil),  // 0: pbout.CreateXlsxFileRequest
	(*CreateXlsxFileResponse)(nil), // 1: pbout.CreateXlsxFileResponse
	(*schemas.Columns)(nil),        // 2: sample.columns
}
var file_xlsxserver_proto_depIdxs = []int32{
	2, // 0: pbout.CreateXlsxFileRequest.cols:type_name -> sample.columns
	0, // 1: pbout.SaveInGRPCServer.PersistValues:input_type -> pbout.CreateXlsxFileRequest
	1, // 2: pbout.SaveInGRPCServer.PersistValues:output_type -> pbout.CreateXlsxFileResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_xlsxserver_proto_init() }
func file_xlsxserver_proto_init() {
	if File_xlsxserver_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_xlsxserver_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateXlsxFileRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_xlsxserver_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateXlsxFileResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_xlsxserver_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_xlsxserver_proto_goTypes,
		DependencyIndexes: file_xlsxserver_proto_depIdxs,
		MessageInfos:      file_xlsxserver_proto_msgTypes,
	}.Build()
	File_xlsxserver_proto = out.File
	file_xlsxserver_proto_rawDesc = nil
	file_xlsxserver_proto_goTypes = nil
	file_xlsxserver_proto_depIdxs = nil
}
